# -*- coding: utf-8 -*-
"""primeiro contato com python.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1VXBOjL5oSpUN5LG8bStvGuOdYTDNVE14
"""

print("Olá, mundo")